import { _electron as electron, expect, test } from "@playwright/test";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { AssetStore } from "../../electron/assets";
import { createBook } from "../../src/shared/books";
import { createNote } from "../../src/shared/notes";
import { assetMarkdown } from "../../src/shared/assets";

test("image settings, duplicate choices and cross-Book deletion filters",async({},info)=>{
  const officialCatalog=JSON.parse(await fs.readFile(path.resolve("resources/starter-content/assets.json"),"utf8"));
  const officialIds=new Set<string>(officialCatalog.assets.map((asset:{id:string})=>asset.id));
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),"lancarbon-resource-management-"));
  const store=new AssetStore(dir),image=await store.importBytes("image.png",await fs.readFile("build/icon.png"),true);
  const userAssets=async()=>(await store.list()).filter(asset=>!officialIds.has(asset.id));
  const shared=await store.importBytes("shared.txt",Buffer.from("original"),false);
  await store.importBytes("unused.txt",Buffer.from("unused"),false);
  const first=createBook("Book A"),second=createBook("Book B"),loose=createNote({title:"Ordinary note",content:assetMarkdown(shared)});
  first.homeNote.content=assetMarkdown(image)+"\n\n"+assetMarkdown(shared);second.homeNote.content=assetMarkdown(shared);
  await fs.writeFile(path.join(dir,"notes.json"),JSON.stringify({version:2,books:[first.book,second.book],notes:[first.homeNote,second.homeNote,loose]}));
  const input=path.join(dir,"shared.txt");await fs.writeFile(input,"incoming");
  const launch=()=>electron.launch({...(process.env.E2E_EXECUTABLE?{executablePath:process.env.E2E_EXECUTABLE}:{}),args:["--in-process-gpu","--disable-gpu","--no-sandbox",...(process.env.E2E_EXECUTABLE?[]:[path.resolve(__dirname,"../..")])],env:{...process.env,E2E_USER_DATA_DIR:dir}});
  let app=await launch();
  try {
    let page=await app.firstWindow();
    await page.getByRole("button",{name:"Books",exact:true}).click();
    await page.getByRole("button",{name:"Image settings",exact:true}).click();
    await page.getByLabel("Image width").fill("300px");await page.getByLabel("Image alignment").selectOption("left");await page.getByLabel("Image caption").fill("A caption");
    await page.getByRole("button",{name:"Apply",exact:true}).click();
    await page.getByRole("button",{name:"Preview",exact:true}).click();
    await expect(page.locator(".markdown-preview img")).toHaveCSS("width","300px");
    await expect(page.locator(".markdown-preview img")).toHaveCSS("margin-left","0px");
    await expect(page.getByLabel("Rendered preview")).toContainText("A caption");
    await page.getByRole("button",{name:"Edit",exact:true}).click();
    await page.getByRole("button",{name:"Image settings",exact:true}).click();await expect(page.getByLabel("Image width")).toHaveValue("300px");
    await page.screenshot({path:info.outputPath("image-settings.png")});await page.getByRole("button",{name:"Cancel",exact:true}).click();
    await page.getByLabel("Note content").press("Control+End");
    await page.getByLabel("Note content").press("Enter");
    const mock=async(response:number)=>app.evaluate(({dialog},args)=>{
      dialog.showOpenDialog=(async()=>({canceled:false,filePaths:[args.input]})) as typeof dialog.showOpenDialog;
      dialog.showMessageBox=(async(...values:unknown[])=>{(globalThis as unknown as {lastDialog:unknown}).lastDialog=values.at(-1);return {response:args.response,checkboxChecked:false};}) as typeof dialog.showMessageBox;
    },{response,input});
    const details=()=>app.evaluate(()=>(globalThis as unknown as {lastDialog?:{detail:string}}).lastDialog?.detail);
    await mock(2);await page.getByRole("button",{name:"Attach file",exact:true}).click();
    const conflict=page.getByRole("dialog",{name:"A resource with this name already exists"});
    await expect(conflict).toContainText("Book B");await expect(conflict).toContainText("Ordinary note");
    await conflict.getByRole("button",{name:"Cancel",exact:true}).click();await expect(conflict).not.toBeVisible();
    await expect(page.getByRole("button",{name:"Attach file",exact:true})).toBeEnabled();
    expect(await userAssets()).toHaveLength(3);
    expect(await details()).toBeUndefined(); // Duplicate imports no longer enter a Windows message-box loop.
    await mock(1);await page.getByRole("button",{name:"Attach file",exact:true}).click();await conflict.getByRole("button",{name:"Keep both",exact:true}).click();await expect(page.getByLabel("Note content")).toContainText("shared (2).txt");
    await fs.writeFile(input,"replacement");await mock(0);await page.getByRole("button",{name:"Attach file",exact:true}).click();
    await conflict.getByRole("button",{name:"Replace existing",exact:true}).click();
    await expect(page.getByRole("button",{name:"Attach file",exact:true})).toBeEnabled();
    await expect.poll(async()=>(await store.read(shared.id).catch(()=>({bytes:Buffer.alloc(0)}))).bytes.toString()).toBe("replacement");
    await page.getByLabel("Note content").click();
    await page.getByLabel("Note content").evaluate(element=>{
      const transfer=new DataTransfer();transfer.items.add(new File(["another drop"],"shared.txt",{type:"text/plain"}));
      element.dispatchEvent(new DragEvent("drop",{dataTransfer:transfer,bubbles:true,cancelable:true}));
    });
    await expect(conflict).toBeVisible();await page.keyboard.press("Escape");await expect(conflict).not.toBeVisible();
    await expect(page.getByLabel("Note content")).toBeFocused();
    await expect(page.getByLabel("Note content")).not.toHaveCSS("cursor","none");
    await page.mouse.move(700,400);await page.getByLabel("Note content").press("End");await page.keyboard.type(" after duplicate drop");
    await expect(page.getByLabel("Note content")).toContainText("after duplicate drop");
    const differentImage=await fs.readFile("resources/starter-content/assets/32a3e216430183b9d8a8b7f239b26b4b0fb164fff5b42f399d119d880c23eb77.png");
    await page.getByLabel("Note content").evaluate((element,base64)=>{
      const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),transfer=new DataTransfer();transfer.items.add(new File([bytes],"image.png",{type:"image/png"}));
      element.dispatchEvent(new DragEvent("drop",{dataTransfer:transfer,bubbles:true,cancelable:true}));
    },differentImage.toString("base64"));
    await expect(conflict).toContainText("image.png");await page.keyboard.press("Escape");await expect(conflict).not.toBeVisible();
    await expect(page.getByLabel("Note content")).toBeFocused();await page.getByLabel("Note content").press("End");await page.keyboard.type(" after duplicate image");
    await expect(page.getByLabel("Note content")).toContainText("after duplicate image");
    await page.getByRole("button",{name:"Resources",exact:true}).click();
    await page.getByLabel("Resource scope").selectOption(`book:${second.book.id}`);
    await expect(page.locator(".asset-row")).toHaveCount(1);
    await mock(1);await page.locator(".asset-row").getByRole("button",{name:"Delete",exact:true}).click();
    await expect.poll(details).toContain("Ordinary note");expect(await userAssets()).toHaveLength(4);
    await page.getByLabel("Resource scope").selectOption("unused");
    await expect(page.locator(".asset-row")).toHaveCount(1);await expect(page.locator(".asset-row")).toContainText("unused.txt");
    await page.getByLabel("Select all visible resources").check();await mock(0);
    await page.getByRole("button",{name:"Delete selected (1)",exact:true}).click();
    await expect(page.locator(".asset-row")).toHaveCount(0);
    await page.getByLabel("Resource scope").selectOption("notes");await expect(page.locator(".asset-row")).toHaveCount(1);
    await page.screenshot({path:info.outputPath("resource-filters.png")});
    await page.locator(".asset-row").getByRole("button",{name:"Delete",exact:true}).click();await expect(page.locator(".asset-row")).toHaveCount(0);
    await expect(store.read(shared.id)).rejects.toThrow("not in the asset catalog");
    await page.getByLabel("Close resources").click();await expect(page.getByLabel("Note content")).not.toContainText(shared.id);
    const saved=JSON.parse(await fs.readFile(path.join(dir,"notes.json"),"utf8"));
    expect(saved.notes.every((n:{content:string})=>!n.content.includes(shared.id))).toBe(true);
    await page.getByRole("button",{name:"☀ Light",exact:true}).click();
    await page.getByRole("button",{name:"Image settings",exact:true}).click();
    await page.screenshot({path:info.outputPath("image-settings-light.png")});
    await page.getByRole("button",{name:"Cancel",exact:true}).click();
    await app.close();app=await launch();page=await app.firstWindow();await page.getByRole("button",{name:"Books",exact:true}).click();
    await page.getByRole("button",{name:"Preview",exact:true}).click();await expect(page.locator(".markdown-preview img")).toHaveCSS("width","300px");
    await expect(page.locator(".preview-diagnostics")).not.toBeVisible();
    const restarted=JSON.parse(await fs.readFile(path.join(dir,"notes.json"),"utf8"));
    expect(restarted.notes.every((n:{content:string})=>!n.content.includes(shared.id))).toBe(true);
    expect((await userAssets()).map(a=>a.name).sort()).toEqual(["image.png","shared (2).txt"]);
  } finally {await app.close().catch(()=>undefined);await fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:500});}
});
