// @vitest-environment node
import { afterEach, expect, it } from "vitest";
import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { AssetStore } from "../electron/assets";
import { exportBookToDirectory } from "../electron/book-exporter";
import { DataLocationManager } from "../electron/data-location";
import { assetMarkdown, assetReferences, mapAssetLinks } from "../src/shared/assets";
import { addNoteToBook, createBook } from "../src/shared/books";
import { createNote } from "../src/shared/notes";
const directories: string[] = [];
async function temporary() { const dir = await fs.mkdtemp(path.join(os.tmpdir(),"lancarbon-assets-")); directories.push(dir); return dir; }
afterEach(async () => { for (const dir of directories.splice(0)) await fs.rm(dir,{recursive:true,force:true}); });
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2XcAAAAASUVORK5CYII=", "base64");
it("keeps imported copies across restart, deduplicates, and separates equal file names", async () => {
  const directory = await temporary(), store = new AssetStore(directory);
  const first = await store.importBytes("中文 图.png",png,true);
  const same = await store.importBytes("other.png",png,true);
  expect(first.id).toBe(same.id);
  const a = await store.importBytes("report.txt",Buffer.from("A"),false);
  const b = await store.importBytes("report.txt",Buffer.from("B"),false);
  expect(a.id).not.toBe(b.id);
  expect((await new AssetStore(directory).read(first.id)).bytes).toEqual(png);
  await expect(store.read("../notes.json")).rejects.toThrow("Invalid asset");
  await expect(store.importBytes("fake.png",Buffer.from("<script>bad</script>"),true)).rejects.toThrow("Choose a PNG");
  await fs.writeFile(path.join(directory,"assets",a.id),"altered");
  await expect(store.read(a.id)).rejects.toThrow("damaged");
});
it("rewrites destinations without changing literal code or the Markdown label", () => {
  const id = "a".repeat(64)+".png", url = "assets/"+id;
  const source = `![${url}](${url})\n\n\`![literal](${url})\`\n\n\`\`\`text\n![literal](${url})\n\`\`\`\n\n[ref]: ${url}\n\n\`\`\`{figure} ${url}\nCaption\n\`\`\``;
  expect(assetReferences(source)).toHaveLength(3);
  const changed = mapAssetLinks(source,id=>"../../assets/"+id);
  expect(changed).toContain(`![${url}](../../${url})`);
  expect(changed).toContain(`\`![literal](${url})\``);
  expect(changed).toContain(`text\n![literal](${url})`);
  expect(changed).toContain(`{figure} ../../${url}`);
});
it("exports nested pages and bytes portably and refuses missing resources before writing", async () => {
  const directory = await temporary(), store = new AssetStore(directory);
  const asset = await store.importBytes("diagram.png",png,true);
  const {book: original,homeNote} = createBook("Portable");
  const note = createNote({title:"Nested",content:assetMarkdown(asset)});
  const book = addNoteToBook(original,note);
  Object.values(book.pages).find(p=>p.noteId===note.id)!.exportPath="chapter/deep/page.md";
  const workspace = {version:2 as const,books:[book],notes:[homeNote,note]};
  const destination = await temporary();
  await exportBookToDirectory(workspace,book.id,destination,store);
  const relocated = path.join(await temporary(),"moved"); await fs.rename(destination,relocated);
  expect(await fs.readFile(path.join(relocated,"chapter/deep/page.md"),"utf8")).toContain(`../../assets/${asset.id}`);
  expect(await fs.readFile(path.join(relocated,"assets",asset.id))).toEqual(png);
  await fs.unlink(path.join(directory,"assets",asset.id));
  const empty = await temporary();
  await expect(exportBookToDirectory(workspace,book.id,empty,store)).rejects.toThrow("Missing or damaged");
  expect(await fs.readdir(empty)).toEqual([]);
});
it("carries the catalog and resource files when the data directory changes", async () => {
  const source=await temporary(), target=await temporary(), config=await temporary();
  await fs.writeFile(path.join(source,"notes.json"),JSON.stringify({version:2,books:[],notes:[]}));
  const asset=await new AssetStore(source).importBytes("copy.png",png,true);
  await new DataLocationManager(config,source,source).prepareTarget(source,target);
  expect((await new AssetStore(target).read(asset.id)).bytes).toEqual(png);
});
it("supports cancel, numbered copies and shared replacement without rewriting reference IDs",async()=>{
  const root=await temporary(),store=new AssetStore(root);
  const first=await store.importBytes("report.txt",Buffer.from("old"),false);
  await expect(store.importBytes("report.txt",Buffer.from("new"),false,async()=>"cancel")).rejects.toThrow("Import canceled");
  expect(await store.list()).toHaveLength(1);
  const second=await store.importBytes("report.txt",Buffer.from("new"),false,async()=>"keep");
  expect(second.name).toBe("report (2).txt");expect(second.id).not.toBe(first.id);
  const replaced=await store.importBytes("report.txt",Buffer.from("replacement"),false,async()=>"replace");
  expect(replaced.id).toBe(first.id);
  expect((await new AssetStore(root).read(first.id)).bytes.toString()).toBe("replacement");
  expect((await store.read(second.id)).bytes.toString()).toBe("new");
  const {book,homeNote}=createBook("Replacement export");
  homeNote.content=assetMarkdown(first);
  const destination=await temporary();
  await exportBookToDirectory({version:2,books:[book],notes:[homeNote]},book.id,destination,store);
  expect((await fs.readFile(path.join(destination,"assets",first.id))).toString()).toBe("replacement");
  expect(await fs.stat(path.join(root,"assets",first.id)).catch(()=>null)).toBeNull();
});
it("deletes selected records and files but preserves shared bytes until the final record is deleted",async()=>{
  const root=await temporary(),store=new AssetStore(root);
  const first=await store.importBytes("same.txt",Buffer.from("same"),false);
  const second=await store.importBytes("same.txt",Buffer.from("same"),false,async()=>"keep");
  expect(second.name).toBe("same (2).txt");
  expect(await store.remove([first.id],async()=>false)).toBe(false);
  expect(await store.list()).toHaveLength(2);
  await expect(store.remove([first.id,second.id],async()=>true,async()=>{throw new Error("Save failed");})).rejects.toThrow("Save failed");
  expect((await store.read(first.id)).bytes.toString()).toBe("same");
  expect(await store.list()).toHaveLength(2);
  await store.remove([first.id],async()=>true);
  expect((await store.read(second.id)).bytes.toString()).toBe("same");
  await store.remove([second.id],async()=>true);
  expect(await fs.readdir(path.join(root,"assets"))).toEqual([]);
  expect(await store.list()).toEqual([]);
  await expect(store.remove(["../notes.json"],async()=>true)).rejects.toThrow("Invalid");
});
